#!/bin/bash
# arrow-detect.sh: Detects the arrow keys, and a few more.
# Thank you, Sandro Magi, for showing me how.
#set -x
# --------------------------------------------
# Character codes generated by the keypresses.
arrowup='\[A'
arrowdown='\[B'
arrowrt='\[C'
arrowleft='\[D'
home='\[1'
insert='\[2'
delete='\[3'
end='\[4'
pgup='\[5'
pgdown='\[6'
# --------------------------------------------

SUCCESS=0
OTHER=65

echo -n "Press a key...  "
# May need to also press ENTER if a key not listed above pressed.
read -n3 key                      # Read 3 characters.

echo -n "$key" | grep "$arrowup"  #Check if character code detected.
if [ "$?" -eq $SUCCESS ]
then
  echo "Up-arrow key pressed."
  exit $SUCCESS
fi

echo -n "$key" | grep "$arrowdown"
if [ "$?" -eq $SUCCESS ]
then
  echo "Down-arrow key pressed."
  exit $SUCCESS
fi

echo -n "$key" | grep "$arrowrt"
if [ "$?" -eq $SUCCESS ]
then
  echo "Right-arrow key pressed."
  exit $SUCCESS
fi

echo -n "$key" | grep "$arrowleft"
if [ "$?" -eq $SUCCESS ]
then
  echo "Left-arrow key pressed."
  exit $SUCCESS
fi

echo -n "$key" | grep "$insert"
if [ "$?" -eq $SUCCESS ]
then
  echo "\"Insert\" key pressed."
  exit $SUCCESS
fi

echo -n "$key" | grep "$delete"
if [ "$?" -eq $SUCCESS ]
then
  echo "\"Delete\" key pressed."
  exit $SUCCESS
fi

echo -n "$key" | grep "$home"
if [ "$?" -eq $SUCCESS ]
then
  echo "\"Home\" key pressed."
  exit $SUCCESS
fi

echo -n "$key" | grep "$end"
if [ "$?" -eq $SUCCESS ]
then
  echo "\"End\" key pressed."
  exit $SUCCESS
fi

echo -n "$key" | grep "$pgup"
if [ "$?" -eq $SUCCESS ]
then
  echo "\"PgUp\" key pressed."
  exit $SUCCESS
fi

echo -n "$key" | grep "$pgdown"
if [ "$?" -eq $SUCCESS ]
then
  echo "\"PgDown\" key pressed."
  exit $SUCCESS
fi

echo " Some other key pressed."

exit $OTHER
